
### View profile
GET http://localhost:8080/api/users/me


### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test.admin@labmonitor.local",
  "password": "Test123!"
}

### Change password (run login first then copy the token)
POST http://localhost:8080/auth/change-password
Content-Type: application/json
Authorization: Bearer Copy_Token_Here

{
  "oldPassword": "Test123!",
  "newPassword": "NyttLosen456!"
}

### Create user (SUPER_ADMIN only)
POST http://localhost:8080/api/users
Content-Type: application/json
Authorization: Bearer Bearer Copy_Token_Here

{
  "email": "ny.anvandare@labmonitor.local",
  "firstName": "Anna",
  "lastName": "Andersson",
  "password": "TempLosen123!",
  "role": "LAB_ADMIN",
  "organizationId": 1
}