spring.application.name=labmonitor

# MySQL connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/labmonitor_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=false


spring.docker.compose.enabled=false
# Server
server.port=8080

# Ersätt med ett slumpmässigt värde på minst 32 tecken, lägg aldrig detta i git i produktion
jwt.secret=byt-ut-mig-mot-nagot-slumpmassigt-och-langt-nog
jwt.expiration=3600000